### ISSUE TITLE
pdb-clone doesn't install with pip to python2.7

### ISSUE THREAD

**Issue by peteristhegreat** [corpusops/pdbclone#2]
```
$ pip install pdb-clone
Collecting pdb-clone
  Using cached https://files.pythonhosted.org/packages/a8/b2/4f918c0a05cb557f6da                                                                                        c9a5715e4cfbbbf65a6be07946b8ad5a571bb94ad/pdb-clone-1.10.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8EhDYV/pdb-clone/setup.py", line 12, in <module>
        from test import test_support as support    # Python 2
      File "/home/....../lib/python2.7/test/te                                                                                        st_support.py", line 2, in <module>
        import test.support
    ImportError: No module named support
```

https://github.com/ContinuumIO/anaconda-issues/issues/168#issuecomment-119056763

Dropping the import of `test.support` in setup.py fixes it.

**Comment by kiorky** [comment]
You miss the python-test pkg of your distribution.
